var score = 0;
function update() {
	var sar = score-parseInt($('#score').text().split("/")[0].split(" ")[1]);
	console.log(sar);
	if(sar>0){
		$("#scoreMod").text(sar);
		$("#scoreMod").css("top", "25px");
		$("#scoreMod").css("opacity", 1);
		$("#scoreMod").animate({top: "-50px", opacity: 0}, 600);
	}
	document.getElementById("score").innerHTML = "Score: "+score+"/"+num;
	if(score == num){
		alert("Good Job!!!");
		document.getElementById("totallySecretTitle").innerHTML = songTitle;
		$("#secretKiller").css("visibility","hidden");
		timerOn = false;
	}
}

// Temporarily a hard static source of data, until we get the API to work.
function getSong(){
	var songs = [["Billy Joel - Piano Man","It's nine o'clock on a Saturday The regular crowd shuffles in There's an old man sitting next to me Making love to his tonic and gin He says, \"Son can you play me a memory I'm not really sure how it goes But it's sad and it's sweet And I knew it complete When I wore a younger man's clothes\" Sing us a song you're the piano man Sing us a song tonight Well we're all in the mood for a melody And you've got us feeling alright Now John at the bar is a friend of mine He gets me my drinks for free And he's quick with a joke or to light up your smoke But there's someplace that he'd rather be He says, \"Bill, I believe this is killing me\" As a smile ran away from his face \"Well, I'm sure that I could be a movie star If I could get out of this place\" Now Paul is a real estate novelist Who never had time for a wife And he's talking with Davy, who's still in the Navy And probably will be for life And the waitress is practicing politics As the businessmen slowly get stoned Yes they're sharing a drink they call loneliness But it's better than drinking alone Sing us a song you're the piano man Sing us a song tonight Well we're all in the mood for a melody And you've got us feeling alright It's a pretty good crowd for a Saturday And the manager gives me a smile 'Cause he knows that it's me they've been coming to see To forget about life for a while And the piano sounds like a carnival And the microphone smells like a beer And they sit at the bar and put bread in my jar And say \"Man what are you doing here?\" Sing us a song you're the piano man Well we're all in the mood for a melody And you've got us feeling alright"],
	["Kristen Bell - Do You Wanna Build A Snowman?", "Elsa? Do you wanna build a snowman? Come on lets go and play I never see you anymore Come out the door It's like you've gone away- We used to be best buddies And now we're not I wish you would tell me why!- Do you wanna build a snowman? It doesn't have to be a snowman. Go away, Anna Okay, bye... Do you wanna build a snowman? Or ride our bikes around the halls I think some company is overdue I've started talking to the pictures on the walls- Hang in there, Joan! It gets a little lonely All these empty rooms, Just watching the hours tick by- Tic-Tock, Tic-Tock, Tic-Tock, Tic-Tock, Tic-Tock Elsa? Please, I know you're in there, People are asking where you've been They say \"have courage\", and I'm trying to I'm right out here for you, just let me in We only have each other It's just you and me What are we gonna do? Do you wanna build a Snowman?"],
	["Francis Scott Key - The Star Spangled Banner","Oh, say can you see by the dawn's early light What so proudly we hailed at the twilight's last gleaming? Whose broad stripes and bright stars thru the perilous fight, O'er the ramparts we watched were so gallantly streaming? And the rocket's red glare, the bombs bursting in air, Gave proof through the night that our flag was still there. Oh, say does that star-spangled banner yet wave O'er the land of the free and the home of the brave? On the shore, dimly seen through the mists of the deep, Where the foe's haughty host in dread silence reposes, What is that which the breeze, o'er the towering steep, As it fitfully blows, half conceals, half discloses? Now it catches the gleam of the morning's first beam, In full glory reflected now shines in the stream: 'Tis the star-spangled banner! Oh long may it wave O'er the land of the free and the home of the brave! And where is that band who so vauntingly swore That the havoc of war and the battle's confusion, A home and a country should leave us no more! Their blood has washed out their foul footsteps' pollution. No refuge could save the hireling and slave From the terror of flight, or the gloom of the grave: And the star-spangled banner in triumph doth wave O'er the land of the free and the home of the brave! Oh! thus be it ever, when freemen shall stand Between their loved home and the war's desolation! Blest with victory and peace, may the heav'n rescued land Praise the Power that hath made and preserved us a nation. Then conquer we must, when our cause it is just, And this be our motto: \"In God is our trust.\" And the star-spangled banner in triumph shall wave O'er the land of the free and the home of the brave!"],
	["The Beatles - Hey Jude","Hey Jude, don't make it bad Take a sad song and make it better Remember to let her into your heart Then you can start to make it better Hey Jude, don't be afraid You were made to go out and get her The minute you let her under your skin Then you begin to make it better And anytime you feel the pain, hey Jude, refrain Don't carry the world upon your shoulders For well you know that it's a fool who plays it cool By making his world a little colder Nah nah nah nah nah nah nah nah nah Hey Jude, don't let me down You have found her, now go and get her Remember to let her into your heart Then you can start to make it better So let it out and let it in, hey Jude, begin You're waiting for someone to perform with And don't you know that it's just you, hey Jude, you'll do The movement you need is on your shoulder Nah nah nah nah nah nah nah nah nah yeah Hey Jude, don't make it bad Take a sad song and make it better Remember to let her under your skin Then you'll begin to make it Better better better better better better, oh Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude Nah nah nah nah nah nah, nah nah nah, hey Jude"],
	["Lorde - Royals", "I've never seen a diamond in the flesh I cut my teeth on wedding rings in the movies And I'm not proud of my address, in the torn up town No post code envy But every song's like gold teeth, grey goose, trippin' in the bathroom Blood stains, ball gowns, trashin' the hotel room, We don't care, we're driving cadillacs in our dreams. But everybody's like cristal, maybach, diamonds on your time piece. Jet planes, islands, tigers on a gold leash. We don't care, we aren't caught up in your love affair. And we'll never be royals... It don't run in our blood, That kind of lux just ain't for us. We crave a different kind of buzz. Let me be your ruler, you can call me queen B And baby I'll rule I'll rule I'll rule I'll rule. Let me live that fantasy. My friends and I we've cracked the code. We count our dollars on the train to the party. And everyone who knows us knows that we're fine with this, We didn't come from money. But every song's like gold teeth, grey goose, trippin' in the bathroom. Blood stains, ball gowns, trashin' the hotel room, We don't care, we're driving cadillacs in our dreams. But everybody's like cristal, maybach, diamonds on your time piece. Jet planes, islands, tigers on a gold leash We don't care we aren't caught up in your love affair And we'll never be royals, It don't run in our blood That kind of lux just ain't for us We crave a different kind of buzz. Let me be your ruler, you can call me queen B And baby I'll rule I'll rule I'll rule I'll rule. Let me live that fantasy. Oooh ooooh ohhh We're bigger than we ever dreamed, and I'm in love with being queen. Oooooh ooooh ohhhhh life is great without a care We aren't caught up in your love affair. And we'll never be royals, It don't run in our blood That kind of lux just ain't for us We crave a different kind of buzz Let me be your ruler, you can call me queen B And baby I'll rule I'll rule I'll rule I'll rule, Let me live that fantasy."],
	["OneRepublic - Counting Stars", "Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be counting stars, yeah we'll be counting stars I see this life like a swinging vine Swing my heart across the line In my face is flashing signs Seek it out and ye shall find Old, but I'm not that old Young, but I'm not that bold I don't think the world is sold I'm just doing what we're told I feel something so right Doing the wrong thing I feel something so wrong Doing the right thing I could lie, could lie, could lie Everything that kills me makes me feel alive Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be counting stars Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be, we'll be counting stars I feel your love and I feel it burn Down this river, every turn Hope is a four-letter word Make that money, watch it burn Old, but I'm not that old Young, but I'm not that bold I don't think the world is sold I'm just doing what we're told I feel something so wrong Doing the right thing I could lie, could lie, could lie Everything that downs me, makes me wanna fly Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be counting stars Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be, we'll be counting stars Take that money Watch it burn Sink in the river The lessons I learned Take that money Watch it burn Sink in the river The lessons I learned Take that money Watch it burn Sink in the river The lessons I learned Take that money Watch it burn Sink in the river The lessons I learned Everything that kills me... makes me feel alive Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be counting stars Lately, I've been, I've been losing sleep Dreaming about the things that we could be But baby, I've been, I've been praying hard, Said no more counting dollars We'll be, we'll be, counting stars Take that money Watch it burn Sink in the river The lessons I learned Take that money Watch it burn Sink in the river The lessons I learned Take that money Watch it burn Sink in the river The lessons I learned Take that money Watch it burn Sink in the river The lessons I learned"],
	["Susan Eegan - I Won't Say I'm in Love","If there's a prize for rotten judgement I guess I've already won that No man is worth the aggravation That's ancient history, been there, done that! Who'd'ya think you're kiddin' He's the Earth and heaven to you Try to keep it hidden Honey, we can see right through you Girl, ya can't conceal it We know how ya feel and Who you're thinking of No chance, no way I won't say it, no, no You swoon, you sigh why deny it, uh-oh It's too cliche I won't say I'm in love I thought my heart had learned its lesson It feels so good when you start out My head is screaming get a grip, girl Unless you're dying to cry your heart out Oh You keep on denying Who you are and how you're feeling Baby, we're not buying Hon, we saw ya hit the ceiling Face it like a grown-up When ya gonna own up That ya got, got, got it bad No chance, no way I won't say it, no, no Give up, give in Check the grin you're in love This scene won't play, I won't say I'm in love You're doin flips read our lips You're in love You're way off base I won't say it Get off my case I won't say it Girl, don't be proud It's O.K. you're in love Oh At least out loud, I won't say I'm in love"],
	["David Tomlinson - Let's Go Fly a Kite","With tuppence for paper and strings You can have your own set of wings With your feet on the ground You're a bird in a flight With your fist holding tight To the string of your kite Oh, oh, oh! Let's go fly a kite Up to the highest height! Let's go fly a kite and send it soaring Up through the atmosphere Up where the air is clear Oh, let's go fly a kite! When you send it flyin' up there All at once you're lighter than air You can dance on the breeze Over 'ouses and trees With your fist 'olding tight To the string of your kite Oh, oh, oh! Let's go fly a kite Up to the highest height! Let's go fly a kite and send it soaring Up through the atmosphere Up where the air is clear Let's go fly a kite!"],
	["Men Without Hats - Safety Dance","We can dance if we want to We can leave your friends behind 'Cause your friends don't dance and if they don't dance Well, they're no friends of mine Say, we can go where we want to A place where they will never find And we can act like we come from out of this world Leave the real one far behind And we can dance Or sing! We can go when we want to The night is young and so am I And we can dress real neat from our hats to our feet And surprise 'em with the victory cry Say, we can act if we want to If we don't, nobody will And you can act real rude and totally removed And I can act like an imbecile And say, we can dance, we can dance Everything's out of control We can dance, we can dance They're doing it from pole to pole We can dance, we can dance Everybody look at your hands We can dance, we can dance Everybody's taking the chance Safety dance Oh well, the safety dance Ah yes, the safety dance We can dance if we want to We've got all your life and mine As long as we abuse it, never gonna lose it Everything'll work out right I say, we can dance if we want to We can leave your friends behind Because your friends don't dance and if they don't dance Well, they're no friends of mine I say, we can dance, we can dance Everything's out of control We can dance, we can dance We're doing it from pole to pole We can dance, we can dance Everybody look at your hands We can dance, we can dance Everybody's taking the chance Oh well, the safety dance Ah yes, the safety dance Oh well, the safety dance Oh well, the safety dance Oh yes, the safety dance Oh, the safety dance, yeah Well, it's the safety dance It's the safety dance Well, it's the safety dance Oh, it's the safety dance Oh, it's the safety dance Oh, it's the safety dance"],
	["Darude - Sandstorm","OM dundun dundun dundun BEEP dun dun dun dun dun dun dun BEEP BEEP BEEP BEEP BEEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BOOM daddaddadadsadadadadadadadadadaddadadadadadaddadadaddadadadadadadadadadadadaddadddadaddadadadd dadadadaddaddada d dadadddaddadaddadadadddadadada nyu nyu nyu nyu nyu nnyu nyu nyu nyu nyu nyu nyu nyu nyu nyu nyu doo doo doo doo doo doo doo doo nnn nn nn nn nn nn n nn nnn nn nn nnn nnn nnnnnnnn dddddddd ddadadadadaddadadadadadaadadadadadad BOOM nyu nyu nyu nyu nyu nyu BOOM BOOM BOOM BOOM BOOM BOOM nyunyunyu nyu nyu nyu nyu nyu nyu nyu nyu nyu nyu BOOM BOOM BEEP BEEP BEEP BEEP BEEP dadadadadada ddadad BOOM BOOM BBEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BEEP BOOM ddudndundun dun dun dun dun dun dun dun dun dun dun dun dun dun dun dund dododododododododododododododododododododododododododododoodo DRUM DRUM DRUM ddodododododoododododododododoodododododododo chi chi chi chi chi chih BOOOM chcihcihfkdhfdisjfkle dodododododododododododododododododododododododododododododododododoo SCHEW dododododododoodododododododododododododo dadadadddudndundundudnudndundundunddunfudnundudnudnudndund BOOM FADE"], ["P!nk - Beam Me Up", "There's a whole 'nother conversation going on In a parallel universe.  Where nothing breaks and nothing hurts.  There's a waltz playin' frozen in time Blades of grass on tiny bare feet I look at you and you're lookin' at me.  Could you beam me up, Give me a minute, I don't know what I'd say in it I'd probably just stare, happy just to be there, holding your face Beam me up, Let me be lighter, I'm tired of being a fighter, I think a minute's enough, Just beam me up.  Saw a blackbird soarin' in the sky, Barely a breath I caught one last sight Tell me that was you sayin' goodbye, There are times I feel the shiver and cold, It only happens when I'm on my own, That's how you tell me I'm not alone Could you beam me up, Give me a minute, I don't know what I'd say in it I'd probably just stare, happy just to be there, holding your face Beam me up, Let me be lighter, I'm tired of being a fighter, I think a minute's enough, Just beam me up.  In my head I see your baby blues I hear your voice and I, I break in two and now there's One of me, with you So when I need you can I send you a sign I'll burn a candle and turn off the lights I'll pick a star and watch you shine Just beam me up, Give me a minute, I don't know what I'd say in it I'd probably just stare, happy just to be there, holding your face Beam me up, Let me be lighter, I'm tired of being a fighter, I think, a minute's enough, Beam me up Beam me up Beam me up Could you beam me up."],
	["Motorhead - Ace Of Spades", "If you like to gamble, I tell you I'm your man, You win some, lose some, all the same to me, The pleasure is to play, makes no difference what you say, I don't share your greed, the only card I need is The Ace Of Spades Playing for the high one, dancing with the devil, Going with the flow, it's all the game to me, Seven or Eleven, snake eyes watching you, Double up or quit, double stake or split, The Ace Of Spades You know I'm born to lose, and gambling's for fools, But that's the way I like it baby, I don't wanna live for ever, And don't forget the joker!  Pushing up the ante, I know you wanna see me, Read 'em and weep, the dead man's hand again, I see it in your eyes, take one look and die, The only thing you see, you know it's gonna be, The Ace Of Spades"],
	["Britney Spears - Womanizer", "Superstar Where you from, hows it going?  I know you Gotta clue, what you're doing?  You can play brand new to all the other chicks out here But I know what you are, what you are, baby Look at you Gettin more than just re-up Baby, you Got all the puppets with their strings up Faking like a good one, but I call 'em like I see 'em I know what you are, what you are, baby Womanizer, Woman, Womanizer You're a Womanizer, oh Womanizer oh You're a Womanizer, baby You you you are, You you you are Womanizer, Womanizer, Womanizer (Womanizer) Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are You got me goin' You're oh so charmin' But I can do it Womanizer Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are You say I'm crazy I got your crazy You're nothin' but a Womanizer Daddy-O You got the swagger of champion Too bad for you You just cant find the right companion I guess when you have one too many, makes it hard It could be easy, who you are That's just who you are, baby Lollipop Must mistake me, you're a sucker To think that I Would be a victim not another Say it, play it how you wanna But no way I'm ever gonna fall for you, never you, baby Womanizer, Woman, Womanizer You're a Womanizer, oh Womanizer oh You're a Womanizer, baby You you you are, You you you are Womanizer, Womanizer, Womanizer (Womanizer) Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are You got me goin' You're oh so charmin' But I can do it You Womanizer Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are You say I'm crazy I got your crazy You're nothin' but a Womanizer Maybe if we both lived in a different world (Womanizer, Womanizer, Womanizer, Womanizer) It would be all good, and maybe I could be your girl, but I can't cause we don't Womanizer, Woman, Womanizer You're a Womanizer, oh Womanizer oh You're a Womanizer, baby You you you are, you you you are Womanizer, Womanizer, Womanizer (Womanizer) Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are You got me goin' You're oh so charmin' But I can do it Womanizer Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are You say I'm crazy I got your crazy You're nothin' but a Womanizer Boy, don't try to front I know just what you are Boy, don't try to front I know just what you are Womanizer, Woman, Womanizer You're a Womanizer Oh Womanizer oh You're a Womanizer, baby"]];
	return songs[Math.floor(Math.random()*songs.length)];
}

function parseLyrics(lies){
	var fin={};
	var a=lies.split(" ");
	for (var i = 0; i < a.length; i++) {
		var n = strippinTime(a[i]).toLowerCase();
		if(a[i].length>18){
			var end="";
			for(var j=12; j<a[i].length; j+=12){
				end+=a[i].substring(j-12, j)+"\n";
			}
			a[i]=end;
		}
		if(n.length>12){
			console.log(n);
			n = n.substring(0,2);
		}
		else if(typeof(fin[n])=="function") {
			fin[n]=null;
		}
		if(fin[n]==null){
			fin[n]=[[i,a[i]]];
		}
		else {
			var temp = fin[n];
			var temp2 = [[i,a[i]]];
			fin[n]=temp.concat(temp2);
		}
	}
	return [fin,a.length];
}

function size(obj){
	var size = 0, key;
    for (key in obj) {
        if (obj.hasOwnProperty(key)) size++;
    }
    return size + 1;
}

function checkDatLyric(lyric){
	return lyrics[lyric]!=null;
}

function strippinTime(words){
	return words.replace(/\W/g, '');
}

function getParameterByName(name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
        results = regex.exec(location.search);
    return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}

